---
# This playbook to be run after playbook_init has been run once, and then can be run on its
# own anytime changes need to be made.
- hosts: ckan
  become: true
  vars:
    ve_dir: /usr/lib/ckan/default

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
        enabled: true

    - name: restart solr
      service:
        name: tomcat9
        state: restarted
        enabled: true

    - name: reload ckan
      command: supervisorctl reload

    - name: reload ufw
      ufw:
        state: reloaded

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install packages required for ansible on the remote server
      block:

        - name: Install system packages
          apt:
            name:
              - python3-pip
              - acl
            state: present

        - name: Install psycopg2
          pip:
            name:
              - psycopg2-binary
              - lxml
            state: present

  roles:
    - users
    - hardening
    - base
    - dvrpc_theme
    - scheming
    - harvest
    - pdfview
    - geoview

  tasks:
    - name: Set up tls
      include_role:
        name: base
        tasks_from: tls_cert
      when: server == "internal" or server == "public"

    - name: Set up oauth for internal instance
      include_role:
        name: oauth
      when: server == "internal"

    # - name: Set up showcases for internal instance
    #   include_role:
    #     name: showcases
    #   when: server == "internal"

    - name: Set up GIS harvester for internal instance
      include_role:
        name: dvrpc_gis_harvester
      when: server == "internal"

    - name: Set up custom privileges for internal instance
      include_role:
        name: custom_privileges
      when: server == "internal"

    - name: Password protect site public site (temporarily)
      include_role:
        name: base
        tasks_from: add_basic_auth
      when: server == "public"

    # - name: Remove password protection
    #   include_role:
    #     name: base
    #     tasks_from: remove_basic_auth
    #   when: server == "public"
