---
# TODO: add the cronjobs on the harvest tasks.yaml file

- hosts: ckan
  become: true
  vars:
    ve_dir: /usr/lib/ckan/default

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: true

    - name: restart solr
      service:
        name: tomcat9
        state: restarted
        enabled: true

    - name: reload ckan
      command: supervisorctl reload

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install packages required for ansible on the remote server
      block:

        - name: Install system packages
          apt:
            name:
              - python3-pip
              - acl
            state: present

        - name: Install psycopg2
          pip:
            name:
              - psycopg2-binary
              - lxml
            state: present
  roles:
    - base
    - custom_privileges
    - dvrpc_theme
    - showcases
    - scheming
    - harvest
    - dvrpc_gis_harvester
