---
# This playbook to be run after playbook_init has been run once, and then can be run on its
# own anytime changes need to be made.
- hosts: ckan
  become: true
  vars:
    ve_dir: /usr/lib/ckan/default

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
        enabled: true

    - name: restart solr
      service:
        name: tomcat9
        state: restarted
        enabled: true

    - name: reload ckan
      command: supervisorctl reload

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: Install packages required for ansible on the remote server
      block:

        - name: Install system packages
          apt:
            name:
              - python3-pip
              - acl
            state: present

        - name: Install psycopg2
          pip:
            name:
              - psycopg2-binary
              - lxml
            state: present

  roles:
    - users
    - role: hardening
      tags: hardening
    - base
    - dvrpc_theme
    - scheming
    - harvest
    - dvrpc_gis_harvester
    - pdfview
    - geoview
    - custom_privileges
    - showcases

  tasks:
    - name: Set up nginx for dev servers
      include_role:
        name: base
        tasks_from: nginx_dev
      when: env == "development"

    - name: Set up nginx/letsencrypt tls cert
      include_role:
        name: base
        tasks_from: tls
      tags:
        - tls
      when: env == "production"

    - name: Set up oauth
      include_role:
        name: oauth
      when: env == "production"
