---
- name: Create directory to put ssh keys into
  file:
    path: /ssh_keys
    state: directory
    mode: 0755

# the public key was added to the repo's deploy keys
- name: Copy private ssh deploy key to server
  copy:
    src: files/ckan_dvrpc_theme_repo
    dest: /ssh_keys/ckan_dvrpc_theme_repo
    mode: 0600

- name: Clone our theme plugin repo
  git:
    repo: git@github.com:dvrpc/ckanext-dvrpc_theme
    dest: /usr/lib/ckan/default/src/ckanext-dvrpc_theme/
    accept_hostkey: true
    key_file: /ssh_keys/ckan_dvrpc_theme_repo

- name: Install the plugin
  pip:
    name: /usr/lib/ckan/default/src/ckanext-dvrpc_theme/
    editable: true
    virtualenv: "{{ ve_dir }}"

- name: Update the solr schema to indicate that category field is multi-value
  xml:
    path: /etc/solr/conf/schema.xml
    xpath: /schema/fields/field
    insertafter: true
    input_type: xml
    add_children:
      <field name="category" type="string" indexed="true" stored="false" multiValued="true"/>
  notify: restart solr

- name: Update ckan.ini (excluding plugin list)
  ini_file:
    path: /etc/ckan/default/ckan.ini
    section: app:main
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    backup: true
  loop: "{{ ini_content | dict2items }}"
  vars:
    ini_content:
      scheming.dataset_schemas: ckanext.dvrpc_theme:dvrpc_dataset.json
      scheming.presets: ckanext.dvrpc_theme:presets.json ckanext.scheming:presets.json
