---
# hardening tasks specific to internal production instance
- name: Allow http/s from within DVRPC firewall and public instance
  ufw:
    rule: allow
    to_port: "{{ item.port }}"
    proto: tcp
    from_ip: "{{ item.ip }}"
  loop:
    - {port: 80, ip: '192.168.200.1'}
    - {port: 443, ip: '192.168.200.1'}
    - {port: 80, ip: '142.93.70.150'}
    - {port: 443, ip: '142.93.70.150'}
  notify: reload ufw

- name: Reject all other http/s
  ufw:
    rule: reject
    to_port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443
  notify: reload ufw
