---
# tasks file for hardening
- name: Install system packages
  apt:
    name:
      - fail2ban
      - ufw
    state: latest

- name: Upgrade system packages
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400  # one day
    autoremove: true

- name: Enable firewall
  ufw:
    state: enabled

- name: Limit ssh connections
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  notify: reload ufw

- name: Hardening
  include_tasks: public.yml
  when: env in ["production", "staging"]

- name: Hardening
  include_tasks: private.yml
  when: env == "development"
