---
# tasks file for hardening
- name: Install system packages
  apt:
    name:
      - fail2ban
      - ufw
    state: latest

- name: Upgrade system packages
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400  # one day
    autoremove: true

- name: Enable firewall
  ufw:
    state: enabled

- name: Limit ssh connections
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  notify: reload ufw

- name: Hardening for internal production instance
  include_tasks: internal_prod.yml
  when: env == "production" and instance == "internal"

- name: Hardening for public production instance
  include_tasks: public_prod.yml
  when: env == "production" and instance == "public"
