---
# hardening tasks specific to public production instance
- name: Allow http/s through firewall
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443
  notify: reload ufw

- name: Deny all other incoming access
  ufw:
    state: enabled
    direction: incoming
    policy: deny
  notify: reload ufw

- name: Limit ssh access to ip4, disable root login, set a timeout on idle connection
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: reload sshd

- name: Configure fail2ban
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0644
  notify: restart fail2ban
