# handlers for the harvest role
- name: Restart ckan_gather_consumer
  supervisorctl:
    name: ckan_gather_consumer
    start: restarted

- name: Restart ckan_fetch_consumer
  supervisorctl:
    name: ckan_fetch_consumer
    start: restarted
