---
- name: Clone our customuserprivileges plugin repo
  git:
    repo: https://github.com/dvrpc/ckanext-customuserprivileges
    dest: /usr/lib/ckan/default/src/ckanext-customuserprivileges
  register: repo

- name: Install the plugin
  pip:
    name: /usr/lib/ckan/default/src/ckanext-customuserprivileges
    editable: true
    virtualenv: "{{ ve_dir }}"
  when: repo.changed or ckan_package.changed

- name: Add plugin to ckan.ini
  lineinfile:
    path: /etc/ckan/default/ckan.ini
    backrefs: true
    regexp: "^(.*ckan.plugins = .*)$"
    line: '\1 customuserprivileges'
