---
# tasks file for dvrpc_gis_harvester - install and configure DVRPC custom profile
- name: Clone plugin repo
  git:
    repo: https://github.com/dvrpc/ckanext-dvrpc_gis_harvester
    dest: /usr/lib/ckan/default/src/ckanext-dvrpc_gis_harvester
  register: repo

- name: Install the plugin
  pip:
    name: /usr/lib/ckan/default/src/ckanext-dvrpc_gis_harvester
    editable: true
    virtualenv: "{{ ve_dir }}"
  when: repo.changed

- name: Add profile to ckan.ini
  ini_file:
    path: /etc/ckan/default/ckan.ini
    section: app:main
    option: ckanext.dcat.rdf.profiles
    value: euro_dcat_ap gis_profile
