---
# tasks file for dvrpc_gis_harvester - install and configure DVRPC custom profile
- name: Clone plugin repo
  git:
    repo: https://github.com/dvrpc/ckanext-dvrpc_gis_harvester
    dest: /usr/lib/ckan/default/src/ckanext-dvrpc_gis_harvester
    version: "{{ dvrpc_git_branch }}"
  register: repo

- name: Install the plugin
  pip:
    name: /usr/lib/ckan/default/src/ckanext-dvrpc_gis_harvester
    editable: true
    virtualenv: "{{ ve_dir }}"
  when: repo.changed or ckan_package.changed

- name: Add profile to ckan.ini
  ini_file:
    path: /etc/ckan/default/ckan.ini
    section: app:main
    option: ckanext.dcat.rdf.profiles
    value: euro_dcat_ap gis_profile

- name: Increase size of resource_proxy file (for previewing larger resources)
  ini_file:
    path: /etc/ckan/default/ckan.ini
    section: app:main
    option: ckan.resource_proxy.max_file_size
    value: 26214400

- name: Create cronjob to clear and reimport GIS datasets
  cron:
    name: "Clear and reimport GIS datasets"
    minute: "0"
    hour: "2"
    day: "*"
    month: "*"
    weekday: "6" # Sunday
    job: 'ckan harvester source clear {{ harvest_source_id }} && (ckan harvester job-abort {{ harvest_source_id }} || true) && (ckan harvester abort-failed-jobs || true) && ckan harvester job {{ harvest_source_id }}' 
    user: root
