---
- name: Install and configure ckanext-harvest plugin
  block:
    - name: Clone harvest plugin repo
      git:
        repo: https://www.github.com/ckan/ckanext-harvest
        dest: /usr/lib/ckan/default/src/ckanext-harvest/
      register: harvest_repo
      notify:
        - restart ckan_gather_consumer
        - restart ckan_fetch_consumer

    - name: Install the plugin
      pip:
        name: /usr/lib/ckan/default/src/ckanext-harvest/
        editable: true
        virtualenv: "{{ ve_dir }}"
      when: harvest_repo.changed

    - name: Install its requirements
      pip:
        chdir: /usr/lib/ckan/default/src/ckanext-harvest/
        requirements: pip-requirements.txt
        virtualenv: "{{ ve_dir }}"
      when: harvest_repo.changed

    - name: Install redis
      apt:
        name: redis-server
        state: present

    - name: Set backend type
      ini_file:
        path: /etc/ckan/default/ckan.ini
        section: app:main
        option: ckan.harvest.mq.type
        value: redis
        backup: true

    - name: Set redis url
      ini_file:
        path: /etc/ckan/default/ckan.ini
        section: app:main
        option: ckan.redis.url
        value: redis://localhost:6379/0
        backup: true

    - name: Add plugin to ckan.ini
      lineinfile:
        path: /etc/ckan/default/ckan.ini
        backrefs: true
        regexp: "^(.*ckan.plugins = .*)$"
        line: '\1 harvest ckan_harvester'

    - name: Set up harvester db.
      command: /usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini harvester initdb

- name: Install and configure ckanext-dcat plugin
  block:
    - name: Clone plugin repo
      git:
        repo: https://github.com/ckan/ckanext-dcat
        dest: /usr/lib/ckan/default/src/ckanext-dcat/
      register: dcat_repo
      notify:
        - restart ckan_gather_consumer
        - restart ckan_fetch_consumer

    - name: Install the plugin
      pip:
        name: /usr/lib/ckan/default/src/ckanext-dcat/
        editable: true
        virtualenv: "{{ ve_dir }}"
      when: dcat_repo.changed

    - name: Install its requirements
      pip:
        chdir: /usr/lib/ckan/default/src/ckanext-dcat/
        requirements: requirements.txt
        virtualenv: "{{ ve_dir }}"
      when: dcat_repo.changed

    - name: Add plugins to ckan.ini
      lineinfile:
        path: /etc/ckan/default/ckan.ini
        backrefs: true
        regexp: "^(.*ckan.plugins = .*)$"
        line: '\1 dcat dcat_rdf_harvester dcat_json_harvester dcat_json_interface structured_data '

- name: Upload harvesting conf file
  copy:
    src: files/ckan_harvesting.conf
    dest: /etc/supervisor/conf.d/

- name: Add to supervisorctl
  block:
    - name: Add ckan_gather_consumer
      supervisorctl:
        name: ckan_gather_consumer
        state: present

    - name: Add ckan_fetch_consumer
      supervisorctl:
        name: ckan_fetch_consumer
        state: present
