---
- name: Include secrets
  include_vars: secrets.yml

- name: Create directory to put ssh keys into
  file:
    path: /ssh_keys
    state: directory
    mode: 0755

# the public key was added to the repo's deploy keys
- name: Copy private ssh deploy key to server
  copy:
    src: files/ckan_dvrpc_theme_repo
    dest: /ssh_keys/ckan_dvrpc_theme_repo
    mode: 0600

- name: Clone our theme plugin repo
  git:
    repo: git@github.com:dvrpc/ckanext-dvrpc_theme
    dest: /usr/lib/ckan/default/src/ckanext-dvrpc_theme/
    version: "{{ dvrpc_git_branch }}"
    accept_hostkey: true
    key_file: /ssh_keys/ckan_dvrpc_theme_repo
  register: repo

- name: Install the plugin
  pip:
    name: /usr/lib/ckan/default/src/ckanext-dvrpc_theme/
    editable: true
    virtualenv: "{{ ve_dir }}"
  when: repo.changed or ckan_package.changed
  notify: reload ckan

- name: Register var to check if category already added
  xml:
    path: /etc/solr/conf/schema.xml
    xpath: /schema/fields/field[@name="category"]
    count: true
  register: category_field

- name: Make category a multi-value field
  xml:
    path: /etc/solr/conf/schema.xml
    xpath: /schema/fields
    add_children:
      - field:
          name: "category"
          type: "string"
          indexed: "true"
          stored: "true"
          multiValued: "true"
    pretty_print: true
  when: category_field.count < 1
  notify:
    - restart solr
    - rebuild solr index

- name: Change field from text to string type
  xml:
    path: /etc/solr/conf/schema.xml
    xpath: /schema/fields/dynamicField[@name='res_extras_*']
    attribute: type
    value: string
  notify:
    - restart solr
    - rebuild solr index

- name: Update ckan.ini (excluding plugin list)
  ini_file:
    path: /etc/ckan/default/ckan.ini
    section: app:main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: true
  loop:
    - {
        option: "scheming.dataset_schemas",
        value: "ckanext.dvrpc_theme:{{ scheming_file }}",
      }
    - {
        option: "scheming.presets",
        value: "ckanext.dvrpc_theme:presets.json ckanext.scheming:presets.json",
      }
    - { option: "licenses_group_url", value: "{{ license_url }}" }
    - { option: "ckan.dvrpcthemeplugin.gis_user", value: "{{ gis_user }}" }
    - {
        option: "ckan.dvrpcthemeplugin.gis_password",
        value: "{{ gis_password }}",
      }
    - {
        option: "ckan.extra_resource_fields",
        value: "geo_resolution dataset_level",
      }
    - {
        option: "ckan.dvrpcthemeplugin.datastore_choices_resource",
        value: "b7527368-a39b-4197-bad0-23a728a76bbe",
      }

- name: Add plugins to ckan.ini
  lineinfile:
    path: /etc/ckan/default/ckan.ini
    backrefs: true
    regexp: "^(.*ckan.plugins = .*)$"
    line: '\1 dvrpc_theme dvrpc_package'
