---
# tasks to install the ckanext-geoview plugin
- name: Clone the plugin repo
  git:
    repo: https://github.com/ckan/ckanext-geoview.git
    dest: /usr/lib/ckan/default/src/ckanext-geoview/
  register: repo

- name: Install the plugin
  pip:
    name: /usr/lib/ckan/default/src/ckanext-geoview/
    editable: true
    virtualenv: "{{ ve_dir }}"
  when: repo.changed or ckan_package.changed

# multiple plugins come with this repo, we're interested in geojson_view
- name: Add plugin to ckan.ini
  lineinfile:
    path: /etc/ckan/default/ckan.ini
    backrefs: true
    regexp: "^(.*ckan.plugins = .*)$"
    line: '\1 geojson_view'
  notify: reload ckan

- name: Add to default resource views
  ini_file:
    path: /etc/ckan/default/ckan.ini
    section: app:main
    option: ckan.views.default_views
    value: image_view text_view datatables_view pdf_view geojson_view
    backup: true
  notify: reload ckan

# add map style changes for geojson previewer
- name: Add resource view map styles
  ini_file:
    path: /etc/ckan/default/ckan.ini
    section: app:main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: true
  loop:
    - { option: "ckanext.spatial.common_map.type", value: "custom" }
    - {
        option: "ckanext.spatial.common_map.custom.url",
        value: "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
      }
    - {
        option: "ckanext.spatial.common_map.attribution",
        value: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>',
      }
