---
# temporarily password protect site

# required for putting app behind basic authentication (using the htpasswd module)
- name: Install passlib
  apt:
    name: python3-passlib
    state: present

- name: Add config to nginx file
  blockinfile:
    path: /etc/nginx/sites-enabled/ckan
    insertafter: "location / {"
    block: |2
              auth_basic "Restricted Content";
              auth_basic_user_file /etc/nginx/.htpasswd;
  notify: reload nginx

- name: Add user and pass to .htpasswd
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd
    owner: root
    group: www-data
    mode: 0640
    name: "{{ protected_user }}"
    password: "{{ protected_pass }}"
