---
# tasks to remove previous letsencrypt

- name: Remove directories
  file:
    path: /etc/letsencrypt/
    state: absent

- name: Remove .well-known dir
  file:
    path: /var/www/html/.well-known
    state: absent
