---
# tasks to add wildcard cert and key; https nginx conf
- name: Copy cert file to server
  copy:
    src: dvrpc_wildcard.crt
    dest: /etc/ssl/dvrpc_wildcard.crt
  notify: reload nginx

- name: Copy cert's key to server
  copy:
    src: dvrpc_wildcard.rsa
    dest: /etc/ssl/dvrpc_wildcard.rsa
  notify: reload nginx

- name: Copy https nginx config to server
  template:
    src: nginx_conf_prod_internal.j2
    dest: "/etc/nginx/sites-available/{{ nginx_server_filename }}"
    owner: root
    group: root
    mode: 0640
  notify: reload nginx
