galaxy_info:
  author: Kris Warner
  description: Base install of CKAN
  company: DVRPC
  license: GPL-2.0-only
  min_ansible_version: 2.11
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
  galaxy_tags: []
dependencies: []
