---
# tasks file for dvrpc_internal_harvester - install custom harvester
- name: Clone plugin repo
  git:
    repo: https://github.com/dvrpc/ckanext-dvrpc_internal_harvester
    dest: /usr/lib/ckan/default/src/ckanext-dvrpc_internal_harvester
  register: repo

- name: Install the plugin
  pip:
    name: /usr/lib/ckan/default/src/ckanext-dvrpc_internal_harvester
    editable: true
    virtualenv: "{{ ve_dir }}"
  when: repo.changed or ckan_package.changed

- name: Add plugin to ckan.ini
  lineinfile:
    path: /etc/ckan/default/ckan.ini
    backrefs: true
    regexp: "^(.*ckan.plugins = .*)$"
    line: '\1 dvrpc_internal_harvester dvrpc_internal_ckan_harvester '
