---
- name: Install ckan_scheming.
  hosts: ckan
  become: true

  tasks:
    - name: Clone ckan_scheming repo.
      git:
        repo: https://github.com/ckan/ckanext-scheming/
        dest: /usr/lib/ckan/default/src/ckanext-scheming/
        version: release-2.1.0

    - name: Install the plugin.
      pip:
        name: /usr/lib/ckan/default/src/ckanext-scheming/
        editable: true
        virtualenv: /usr/lib/ckan/default/

    - name: Add plugin to ckan.ini
      ini_file:
        path: /etc/ckan/default/ckan.ini
        section: app:main
        option: ckan.plugins
        value: stats text_view image_view recline_view datastore datapusher scheming_datasets
        backup: true
