---
- name: Install customuserprivileges
  hosts: ckan
  become: true
  vars:
    ve_dir: /usr/lib/ckan/default/bin

  tasks:
    - name: Clone our customuserprivileges plugin repo.
      git:
        repo: https://github.com/dvrpc/ckanext-customuserprivileges
        dest: /usr/lib/ckan/default/src/ckanext-customuserprivileges/

    - name: Install the plugin.
      command:
        chdir: /usr/lib/ckan/default/src/ckanext-customuserprivileges
        cmd: "{{ ve_dir }}/python setup.py develop"

    - name: Add plugin to ckan.ini
      ini_file:
        path: /etc/ckan/default/ckan.ini
        section: app:main
        option: ckan.plugins
        value: stats text_view image_view recline_view datastore datapusher scheming_datasets customuserprivileges dvrpc_theme dvrpc_package
        backup: true
