---
- hosts: ckan
  become: true
  vars:
    ve_dir: /usr/lib/ckan/default/bin

  handlers:
    - name: reload ckan
      command: supervisorctl reload

  # this is a private repo. Not sure if I'll be able to use ssh agent forwarding with this - if not,
  # next step would be to look into deploy keys for this (see notes/2021-06-22-2229.md)
  tasks:
    - name: Create directory to put ssh keys into.
      file:
        path: /ssh_keys
        state: directory
        mode: 0755

    # the public key was added to the repo's deploy keys
    - name: Copy private ssh deploy key to server.
      copy:
        src: files/ckan_dvrpc_theme_repo
        dest: /ssh_keys/ckan_dvrpc_theme_repo
        mode: 0600

    - name: Clone our theme plugin repo.
      git:
        repo: git@github.com:dvrpc/ckanext-dvrpc_theme
        dest: /usr/lib/ckan/default/src/ckanext-dvrpc_theme/
        accept_hostkey: true
        key_file: /ssh_keys/ckan_dvrpc_theme_repo

    # - name: Install the theme plugin.
    #   command:
    #     chdir: /usr/lib/ckan/default/src/ckanext-dvrpc_theme
    #     cmd: "{{ ve_dir }}/python setup.py develop"

    - name: Install the theme plugin.
      pip:
        name: /usr/lib/ckan/default/src/ckanext-dvrpc_theme/
        editable: true
        virtualenv: /usr/lib/ckan/default/

    - name: Add plugin to ckan.ini
      ini_file:
        path: /etc/ckan/default/ckan.ini
        section: app:main
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        backup: true
      loop: "{{ ini_content | dict2items }}"
      vars:
        ini_content:
          ckan.plugins: stats text_view image_view recline_view datastore datapusher dvrpc_theme
          scheming.dataset_schemas: ckanext.dvrpc_theme:dvrpc_dataset.json
          scheming.presets: ckanext.dvrpc_theme:presets.json ckanext.scheming:presets.json
      notify:
        - reload ckan
